security:
    # our local security
    firewalls:
        default:
            remember_me:
                key: "%secret%"

services:
    some_service:
        class: App\SomeService
        public: true
